#!/bin/bash

[ -z "$1" ] && echo "Usage : $0 [ENV_NAME]" && exit 1

! [ -d "$1" ] && echo "$1 does not exist" && exit 2

! [ -f "file_map" ] && echo "file_map not found" && exit 3

[ -z "$HOME" ] && echo "It seems you are a homeless user !" && exit 4

while read l; do
	file=`cut -f1 -d':' <<< $l`
	dest=`cut -f2 -d':' <<< $l`

	dest_dir=`dirname $dest`

	mkdir -p $HOME/$dest_dir
	cp $1/$file $HOME/$dest
done < file_map

exit 0
