#!/bin/bash

[ "$1" == "1" ] && feh --no-fehbg --bg-max '/home/avanzaghi/Pictures/wp/laptop_wp' 
[ "$1" == "2" ] && feh --no-fehbg --bg-max '/home/avanzaghi/Pictures/wp/laptop_wp' --bg-max '/home/avanzaghi/Pictures/wp/wide_wp' 
[ "$1" == "3" ] && feh --no-fehbg --bg-max '/home/avanzaghi/Pictures/wp/laptop_wp' --bg-max '/home/avanzaghi/Pictures/wp/hd_wp' --bg-max '/home/avanzaghi/Pictures/wp/wide_wp' 
